const actionTypes = {
    SET_LIST_VIEW: 'SET_LIST_VIEW',
    SET_SONGS: 'SET_SONGS',
    ADD_FAVORITE_SONG: 'ADD_FAVORITE_SONG',
    REMOVE_FAVORITE_SONG: 'REMOVE_FAVORITE_SONG',
    SET_FAVORITE_SONGS: 'SET_FAVORITE_SONGS',
}

export default actionTypes;